lazy val scala213Version        = "2.13.18"
lazy val scala3LtsVersion       = "3.3.8"
lazy val supportedScalaVersions = List(scala213Version, scala3LtsVersion)

ThisBuild / version          := "0.1.0-SNAPSHOT"
ThisBuild / organization     := "io.moka"
ThisBuild / organizationName := "moka"
ThisBuild / scalaVersion     := scala3LtsVersion

lazy val scalacOptionsCommon = Seq(
  Compile / scalacOptions ++= {
    CrossVersion.partialVersion(scalaVersion.value) match {
      case Some((2, 13)) => List("-Ymacro-annotations", "-Xsource:3")
      // set MOKA_DEBUG=1 to print the trees generated by the macros
      case Some((3, _)) if sys.env.contains("MOKA_DEBUG") =>
        List("-Xprint:postInlining")
      case Some((3, _)) => Nil
      case _            => Nil
    }
  }
)

lazy val root = project
  .settings(
    crossScalaVersions := Nil,
    publish / skip     := true,
    addCommandAlias("run", "examples/run")
  )
  .aggregate(examples, macros)

lazy val examples = project
  .settings(scalacOptionsCommon)
  .settings(
    crossScalaVersions := supportedScalaVersions,
    publish / skip     := true,
    //   scalacOptions += "-Ymacro-debug-lite",
    libraryDependencies += ("org.mongodb.scala" %% "mongo-scala-bson" % "5.5.1")
      .cross(CrossVersion.for3Use2_13),
    // Pinned: 1.0.7 is built on Scala 3.4 and 1.0.8 on 3.5.2, so neither can be
    // read by the 3.3 LTS compiler (TASTy 28.5 vs the 28.3 it expects).
    libraryDependencies += "dev.zio"       %% "zio-bson" % "1.0.6",
    libraryDependencies += "org.scalameta" %% "munit"    % "1.1.1" % Test
  )
  .dependsOn(macros)

lazy val docs = project
  .in(file("moka-docs"))
  .settings(
    crossScalaVersions := supportedScalaVersions,
    publish / skip     := true,
    moduleName         := "moka-docs",
    mdocVariables      := Map("VERSION" -> version.value),
    git.remoteRepo     := "git@github.com:vimalaguti/moka.git"
  )
  .dependsOn(examples)
  .enablePlugins(MdocPlugin, DocusaurusPlugin, GhpagesPlugin)

/** Not aggregated by `root`, so it never runs in CI. Its sources are generated
  * by scripts/gen-bench-model.py and are git-ignored.
  */
lazy val bench = project
  .settings(scalacOptionsCommon)
  .settings(
    crossScalaVersions := supportedScalaVersions,
    publish / skip     := true,
    // measurement noise, and semanticdb-scalac has no build for every 2.13 patch
    semanticdbEnabled := false
  )
  .dependsOn(macros)

/** Runtime benchmark: how much does Scala 3's selectDynamic chain actually cost
  * once the JIT has had a look? Not aggregated by `root`.
  * Run with: sbt "benchJmh/Jmh/run -f1 .*PathBenchmark.*"
  */
lazy val benchJmh = project
  .in(file("bench-jmh"))
  .enablePlugins(JmhPlugin)
  .settings(scalacOptionsCommon)
  .settings(
    crossScalaVersions := supportedScalaVersions,
    publish / skip     := true,
    semanticdbEnabled  := false
  )
  .dependsOn(macros)

lazy val macros = project
  .settings(scalacOptionsCommon)
  .settings(
    crossScalaVersions := supportedScalaVersions,
    name               := "moka",
    libraryDependencies ++= {
      CrossVersion.partialVersion(scalaVersion.value) match {
        case Some((2, 13)) =>
          Seq(
            "org.scala-lang" % "scala-reflect" % scalaVersion.value
          )
        case _ => Seq.empty
      }
    }
  )

// See https://www.scala-sbt.org/1.x/docs/Using-Sonatype.html for instructions on how to publish to Sonatype.
